### ISSUE TITLE
Database Access GitHub Action

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport-actions#11]
Aim to deliver an experience similar to that delivered by https://github.com/gravitational/teleport-actions/pull/8 (Kubernetes access) for Database Access.

```yaml
steps:
  - name: Install Kubectl
    uses: azure/setup-kubectl@v3
  - name: Install Teleport
    uses: gravitational/teleport-actions/setup@v1
    with:
      version: 11.0.3
  - name: Authorize against Teleport
    uses: gravitational/teleport-actions/auth-db@v1
    with:
      # Specify the publically accessible address of your Teleport proxy.
      proxy: tele.example.com:443
      # Specify the name of the join token for your bot.
      token: my-github-join-token
      database-service: my-teleport-db-service
      database: my-db
      database-username: my-username
```

The action should:

- Fetch certificates for the named database
- Use `tsh proxy db`/`tbot proxy db` to open a proxied port that other steps can connect to.
- Use GHA action outputs to provide paths to ports and generated credentials the client needs to use.

Use case:

- Running migrations from a tool like Liquibase.

References:

- https://goteleport.com/docs/machine-id/guides/databases/
