### ISSUE TITLE
Action for authenticating `tsh`/`tctl`

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport-actions#12]
Suggestion for an action for general use (tsh/tctl):

```yaml
steps:
  - name: Install Teleport
    uses: gravitational/teleport-actions/setup@v1
    with:
      version: 11.0.3
  - name: Authorize against Teleport
    uses: gravitational/teleport-actions/auth@v1
    with:
      # Specify the publically accessible address of your Teleport proxy.
      proxy: tele.example.com:443
      # Specify the name of the join token for your bot.
      token: my-github-join-token
  - name: List nodes
     run: tsh ls
```

Some additional work is required to `tsh` and `tctl` to allow them to be automatically configured (via environment variable) with the proxy and identity file locations.

**Comment by strideynet** [comment]
Suggestion for an action for general use (tsh/tctl):

```yaml
steps:
  - name: Install Kubectl
    uses: azure/setup-kubectl@v3
  - name: Install Teleport
    uses: gravitational/teleport-actions/setup@v1
    with:
      version: 11.0.3
  - name: Authorize against Teleport
    uses: gravitational/teleport-actions/auth@v1
    with:
      # Specify the publically accessible address of your Teleport proxy.
      proxy: tele.example.com:443
      # Specify the name of the join token for your bot.
      token: my-github-join-token
  - name: Install Teleport
     run: tsh ls
```

Some additional work is required to `tsh` and `tctl` to allow them to be automatically configured (via environment variable) with the proxy and identity file locations.
